package com.idata.pdm.entity;

import java.util.Date;

public class ActionLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.log_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.actor
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private String actor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.action_date
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Date actionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.ip_address
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private String ipAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.action
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action_log.action_object
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private String actionObject;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.log_id
     *
     * @return the value of action_log.log_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.log_id
     *
     * @param logId the value for action_log.log_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.actor
     *
     * @return the value of action_log.actor
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public String getActor() {
        return actor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.actor
     *
     * @param actor the value for action_log.actor
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setActor(String actor) {
        this.actor = actor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.action_date
     *
     * @return the value of action_log.action_date
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Date getActionDate() {
        return actionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.action_date
     *
     * @param actionDate the value for action_log.action_date
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setActionDate(Date actionDate) {
        this.actionDate = actionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.ip_address
     *
     * @return the value of action_log.ip_address
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.ip_address
     *
     * @param ipAddress the value for action_log.ip_address
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.action
     *
     * @return the value of action_log.action
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.action
     *
     * @param action the value for action_log.action
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setAction(String action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action_log.action_object
     *
     * @return the value of action_log.action_object
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public String getActionObject() {
        return actionObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action_log.action_object
     *
     * @param actionObject the value for action_log.action_object
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setActionObject(String actionObject) {
        this.actionObject = actionObject;
    }
}