package com.idata.pdm.entity;

import java.util.Date;

public class DocumentVersion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_version.document_version_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer documentVersionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_version.document_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_version.upload_date
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Date uploadDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_version.upload_employee
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private String uploadEmployee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document_version.version
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private String version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_version.document_version_id
     *
     * @return the value of document_version.document_version_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getDocumentVersionId() {
        return documentVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_version.document_version_id
     *
     * @param documentVersionId the value for document_version.document_version_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setDocumentVersionId(Integer documentVersionId) {
        this.documentVersionId = documentVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_version.document_id
     *
     * @return the value of document_version.document_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_version.document_id
     *
     * @param documentId the value for document_version.document_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_version.upload_date
     *
     * @return the value of document_version.upload_date
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Date getUploadDate() {
        return uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_version.upload_date
     *
     * @param uploadDate the value for document_version.upload_date
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_version.upload_employee
     *
     * @return the value of document_version.upload_employee
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public String getUploadEmployee() {
        return uploadEmployee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_version.upload_employee
     *
     * @param uploadEmployee the value for document_version.upload_employee
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setUploadEmployee(String uploadEmployee) {
        this.uploadEmployee = uploadEmployee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document_version.version
     *
     * @return the value of document_version.version
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document_version.version
     *
     * @param version the value for document_version.version
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setVersion(String version) {
        this.version = version;
    }
}