package com.idata.pdm.entity;

public class Document {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.document_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer documentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.file_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.folder_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer folderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.document_name
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private String documentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column document.project_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer projectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.document_id
     *
     * @return the value of document.document_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.document_id
     *
     * @param documentId the value for document.document_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.file_id
     *
     * @return the value of document.file_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.file_id
     *
     * @param fileId the value for document.file_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.folder_id
     *
     * @return the value of document.folder_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.folder_id
     *
     * @param folderId the value for document.folder_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setFolderId(Integer folderId) {
        this.folderId = folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.document_name
     *
     * @return the value of document.document_name
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public String getDocumentName() {
        return documentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.document_name
     *
     * @param documentName the value for document.document_name
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setDocumentName(String documentName) {
        this.documentName = documentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column document.project_id
     *
     * @return the value of document.project_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column document.project_id
     *
     * @param projectId the value for document.project_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }
}