package com.idata.pdm.entity;

public class EmployeeProject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_project.employee_project_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer employeeProjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_project.employee_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_project.project_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer projectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_project.employee_project_id
     *
     * @return the value of employee_project.employee_project_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getEmployeeProjectId() {
        return employeeProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_project.employee_project_id
     *
     * @param employeeProjectId the value for employee_project.employee_project_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setEmployeeProjectId(Integer employeeProjectId) {
        this.employeeProjectId = employeeProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_project.employee_id
     *
     * @return the value of employee_project.employee_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_project.employee_id
     *
     * @param employeeId the value for employee_project.employee_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_project.project_id
     *
     * @return the value of employee_project.project_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_project.project_id
     *
     * @param projectId the value for employee_project.project_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }
}