package com.idata.pdm.entity;

public class EmployeeRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_role.employee_role_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer employeeRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_role.role_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_role.employee_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer employeeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_role.employee_role_id
     *
     * @return the value of employee_role.employee_role_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getEmployeeRoleId() {
        return employeeRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_role.employee_role_id
     *
     * @param employeeRoleId the value for employee_role.employee_role_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setEmployeeRoleId(Integer employeeRoleId) {
        this.employeeRoleId = employeeRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_role.role_id
     *
     * @return the value of employee_role.role_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_role.role_id
     *
     * @param roleId the value for employee_role.role_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_role.employee_id
     *
     * @return the value of employee_role.employee_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_role.employee_id
     *
     * @param employeeId the value for employee_role.employee_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }
}