package com.idata.pdm.entity;

public class RoleMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.role_menu_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer roleMenuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.role_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_menu.menu_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.role_menu_id
     *
     * @return the value of role_menu.role_menu_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getRoleMenuId() {
        return roleMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.role_menu_id
     *
     * @param roleMenuId the value for role_menu.role_menu_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setRoleMenuId(Integer roleMenuId) {
        this.roleMenuId = roleMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.role_id
     *
     * @return the value of role_menu.role_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.role_id
     *
     * @param roleId the value for role_menu.role_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_menu.menu_id
     *
     * @return the value of role_menu.menu_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_menu.menu_id
     *
     * @param menuId the value for role_menu.menu_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
}