package com.idata.pdm.entity;

public class TemplateFolder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_folder.template_folder_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer templateFolderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_folder.template_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_folder.template_folder_name
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private String templateFolderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_folder.template_folder_desc
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private String templateFolderDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_folder.template__parent_folder_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private String templateParentFolderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_folder.template_folder_id
     *
     * @return the value of template_folder.template_folder_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getTemplateFolderId() {
        return templateFolderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_folder.template_folder_id
     *
     * @param templateFolderId the value for template_folder.template_folder_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setTemplateFolderId(Integer templateFolderId) {
        this.templateFolderId = templateFolderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_folder.template_id
     *
     * @return the value of template_folder.template_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_folder.template_id
     *
     * @param templateId the value for template_folder.template_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_folder.template_folder_name
     *
     * @return the value of template_folder.template_folder_name
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public String getTemplateFolderName() {
        return templateFolderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_folder.template_folder_name
     *
     * @param templateFolderName the value for template_folder.template_folder_name
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setTemplateFolderName(String templateFolderName) {
        this.templateFolderName = templateFolderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_folder.template_folder_desc
     *
     * @return the value of template_folder.template_folder_desc
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public String getTemplateFolderDesc() {
        return templateFolderDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_folder.template_folder_desc
     *
     * @param templateFolderDesc the value for template_folder.template_folder_desc
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setTemplateFolderDesc(String templateFolderDesc) {
        this.templateFolderDesc = templateFolderDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_folder.template__parent_folder_id
     *
     * @return the value of template_folder.template__parent_folder_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public String getTemplateParentFolderId() {
        return templateParentFolderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_folder.template__parent_folder_id
     *
     * @param templateParentFolderId the value for template_folder.template__parent_folder_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setTemplateParentFolderId(String templateParentFolderId) {
        this.templateParentFolderId = templateParentFolderId;
    }
}