package com.idata.pdm.entity;

public class TemplateDocument {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_document.template_document_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer templateDocumentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_document.template_folder_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer templateFolderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template_document.template_document_name
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer templateDocumentName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_document.template_document_id
     *
     * @return the value of template_document.template_document_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getTemplateDocumentId() {
        return templateDocumentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_document.template_document_id
     *
     * @param templateDocumentId the value for template_document.template_document_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setTemplateDocumentId(Integer templateDocumentId) {
        this.templateDocumentId = templateDocumentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_document.template_folder_id
     *
     * @return the value of template_document.template_folder_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getTemplateFolderId() {
        return templateFolderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_document.template_folder_id
     *
     * @param templateFolderId the value for template_document.template_folder_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setTemplateFolderId(Integer templateFolderId) {
        this.templateFolderId = templateFolderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template_document.template_document_name
     *
     * @return the value of template_document.template_document_name
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getTemplateDocumentName() {
        return templateDocumentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template_document.template_document_name
     *
     * @param templateDocumentName the value for template_document.template_document_name
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setTemplateDocumentName(Integer templateDocumentName) {
        this.templateDocumentName = templateDocumentName;
    }
}