package com.idata.pdm.entity;

public class Template {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.template_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private Integer templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.template_name
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private String templateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.template_desc
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    private String templateDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.template_id
     *
     * @return the value of template.template_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.template_id
     *
     * @param templateId the value for template.template_id
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.template_name
     *
     * @return the value of template.template_name
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.template_name
     *
     * @param templateName the value for template.template_name
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.template_desc
     *
     * @return the value of template.template_desc
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public String getTemplateDesc() {
        return templateDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.template_desc
     *
     * @param templateDesc the value for template.template_desc
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    public void setTemplateDesc(String templateDesc) {
        this.templateDesc = templateDesc;
    }
}