package com.idata.pdm.dao;

import com.idata.pdm.entity.ActionLog;

public interface ActionLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int insert(ActionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int insertSelective(ActionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    ActionLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int updateByPrimaryKeySelective(ActionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_log
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int updateByPrimaryKey(ActionLog record);
}