package com.idata.pdm.dao;

import com.idata.pdm.entity.DocumentVersion;

public interface DocumentVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_version
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int deleteByPrimaryKey(Integer documentVersionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_version
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int insert(DocumentVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_version
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int insertSelective(DocumentVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_version
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    DocumentVersion selectByPrimaryKey(Integer documentVersionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_version
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int updateByPrimaryKeySelective(DocumentVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table document_version
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int updateByPrimaryKey(DocumentVersion record);
}