package com.idata.pdm.dao;

import com.idata.pdm.entity.EmployeeRole;

public interface EmployeeRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_role
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int deleteByPrimaryKey(Integer employeeRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_role
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int insert(EmployeeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_role
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int insertSelective(EmployeeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_role
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    EmployeeRole selectByPrimaryKey(Integer employeeRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_role
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int updateByPrimaryKeySelective(EmployeeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_role
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int updateByPrimaryKey(EmployeeRole record);
}