package com.idata.pdm.dao;

import com.idata.pdm.entity.EmployeeProject;

public interface EmployeeProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_project
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int deleteByPrimaryKey(Integer employeeProjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_project
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int insert(EmployeeProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_project
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int insertSelective(EmployeeProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_project
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    EmployeeProject selectByPrimaryKey(Integer employeeProjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_project
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int updateByPrimaryKeySelective(EmployeeProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_project
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int updateByPrimaryKey(EmployeeProject record);
}