package com.idata.pdm.dao;

import com.idata.pdm.entity.TemplateFolder;

public interface TemplateFolderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_folder
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int deleteByPrimaryKey(Integer templateFolderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_folder
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int insert(TemplateFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_folder
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int insertSelective(TemplateFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_folder
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    TemplateFolder selectByPrimaryKey(Integer templateFolderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_folder
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int updateByPrimaryKeySelective(TemplateFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_folder
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int updateByPrimaryKey(TemplateFolder record);
}