package com.idata.pdm.dao;

import com.idata.pdm.entity.TemplateDocument;

public interface TemplateDocumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_document
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int deleteByPrimaryKey(Integer templateDocumentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_document
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int insert(TemplateDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_document
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int insertSelective(TemplateDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_document
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    TemplateDocument selectByPrimaryKey(Integer templateDocumentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_document
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int updateByPrimaryKeySelective(TemplateDocument record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template_document
     *
     * @mbg.generated Fri Oct 20 17:21:25 CST 2017
     */
    int updateByPrimaryKey(TemplateDocument record);
}